name: CustomItems
main: nl.knokko.customitems.plugin.CustomItemsPlugin
version: "13.4"
softdepend: [KnokkoCore, CrazyEnchantments, ActionBarAPI, Mimic, ItemBridge, WorldGuard, Skript, Denizen, Magic, Geyser-Spigot]
loadbefore: [UltraChest]
api-version: "1.13"
commands:
  customitems:
    description: Commands for the CustomItems plugin
    usage: /kci give/take/list/damage/repair/debug/setblock/encode/reload/container/playsound/tag/magic/resourcepack
    aliases: [ci, kci]
