package nl.knokko.customitems.plugin.set.item;

import java.util.Arrays;

/**
 * <p>
 * Represents the boolean representation of a custom item. This is the data that was
 * generated by the Editor when the custom item was exported. 
 * </p>
 * 
 * <p>
 * To elaborate, take a look at the export(BitOutput) method of the CustomItem class 
 * of the Editor. All custom items will export themselves by writing primitives 
 * (int, String, boolean...) to the given BitOutput instance and BitOutput will 
 * convert all those to a sequence of booleans. This class represents such a sequence 
 * of booleans.
 * </p>
 * 
 * <p>
 * The most interesting part of the boolean representation is that it can be used to
 * recreate the custom item, even from previous versions of the item set.
 * </p>
 */
public class BooleanRepresentation {
	
	private final byte[] byteRepresentation;

	public BooleanRepresentation(byte[] byteRepresentation) {
		this.byteRepresentation = byteRepresentation;
	}
	
	@Override
	public boolean equals(Object other) {
		if (other instanceof BooleanRepresentation) {
			BooleanRepresentation boolRep = (BooleanRepresentation) other;
			return Arrays.equals(byteRepresentation, boolRep.byteRepresentation);
		} else {
			return false;
		}
	}
	
	@Override
	public String toString() {
		return "BooleanRepresentation(" + Arrays.toString(byteRepresentation) + ")";
	}
	
	public byte[] getAsBytes() {
		return byteRepresentation;
	}
}
