name: CustomItems
main: nl.knokko.customitems.plugin.CustomItemsPlugin
version: 8.4
depend: [KnokkoCore]
softdepend: [CrazyEnchantments]
loadbefore: [UltraChest]
commands:
  customitems:
    description: Commands for the CustomItems plugin
    usage: /kci give <item name> [player name] or /kci list or /kci reload or /kci debug
    aliases: [ci, kci]
