package nl.knokko.customitems.item;

import nl.knokko.customitems.NameHelper;

import java.util.ArrayList;
import java.util.List;

import static nl.knokko.customitems.MCVersions.*;

public enum VItemFlag {

	HIDE_ENCHANTS(VERSION1_12, VERSION26),
	HIDE_ATTRIBUTES(VERSION1_12, VERSION26),
	HIDE_UNBREAKABLE(VERSION1_12, VERSION26),
	HIDE_DESTROYS(VERSION1_12, VERSION26),
	HIDE_PLACED_ON(VERSION1_12, VERSION26),
	HIDE_POTION_EFFECTS(VERSION1_12, VERSION1_20),
	HIDE_DYE(VERSION1_16, VERSION26),
	HIDE_ARMOR_TRIM(VERSION1_19, VERSION26),
	HIDE_ADDITIONAL_TOOLTIP(VERSION1_21, VERSION26),
	HIDE_STORED_ENCHANTS(VERSION1_21, VERSION1_21),
	HIDE_CUSTOM_DATA(VERSION26, VERSION26),
	HIDE_MAX_STACK_SIZE(VERSION26, VERSION26),
	HIDE_MAX_DAMAGE(VERSION26, VERSION26),
	HIDE_DAMAGE(VERSION26, VERSION26),
	HIDE_CUSTOM_NAME(VERSION26, VERSION26),
	HIDE_ITEM_NAME(VERSION26, VERSION26),
	HIDE_ITEM_MODEL(VERSION26, VERSION26),
	HIDE_LORE(VERSION26, VERSION26),
	HIDE_RARITY(VERSION26, VERSION26),
	HIDE_ENCHANTMENTS(VERSION26, VERSION26),
	HIDE_CAN_PLACE_ON(VERSION26, VERSION26),
	HIDE_CAN_BREAK(VERSION26, VERSION26),
	HIDE_ATTRIBUTE_MODIFIERS(VERSION26, VERSION26),
	HIDE_CUSTOM_MODEL_DATA(VERSION26, VERSION26),
	HIDE_TOOLTIP_DISPLAY(VERSION26, VERSION26),
	HIDE_REPAIR_COST(VERSION26, VERSION26),
	HIDE_CREATIVE_SLOT_LOCK(VERSION26, VERSION26),
	HIDE_ENCHANTMENT_GLINT_OVERRIDE(VERSION26, VERSION26),
	HIDE_INTANGIBLE_PROJECTILE(VERSION26, VERSION26),
	HIDE_FOOD(VERSION26, VERSION26),
	HIDE_CONSUMABLE(VERSION26, VERSION26),
	HIDE_USE_REMAINDER(VERSION26, VERSION26),
	HIDE_USE_COOLDOWN(VERSION26, VERSION26),
	HIDE_DAMAGE_RESISTANT(VERSION26, VERSION26),
	HIDE_TOOL(VERSION26, VERSION26),
	HIDE_WEAPON(VERSION26, VERSION26),
	HIDE_ENCHANTABLE(VERSION26, VERSION26),
	HIDE_EQUIPPABLE(VERSION26, VERSION26),
	HIDE_REPAIRABLE(VERSION26, VERSION26),
	HIDE_GLIDER(VERSION26, VERSION26),
	HIDE_TOOLTIP_STYLE(VERSION26, VERSION26),
	HIDE_DEATH_PROTECTION(VERSION26, VERSION26),
	HIDE_BLOCKS_ATTACKS(VERSION26, VERSION26),
	HIDE_STORED_ENCHANTMENTS(VERSION26, VERSION26),
	HIDE_DYED_COLOR(VERSION26, VERSION26),
	HIDE_MAP_COLOR(VERSION26, VERSION26),
	HIDE_MAP_ID(VERSION26, VERSION26),
	HIDE_MAP_DECORATIONS(VERSION26, VERSION26),
	HIDE_MAP_POST_PROCESSING(VERSION26, VERSION26),
	HIDE_CHARGED_PROJECTILES(VERSION26, VERSION26),
	HIDE_BUNDLE_CONTENTS(VERSION26, VERSION26),
	HIDE_POTION_CONTENTS(VERSION26, VERSION26),
	HIDE_POTION_DURATION_SCALE(VERSION26, VERSION26),
	HIDE_SUSPICIOUS_STEW_EFFECTS(VERSION26, VERSION26),
	HIDE_WRITABLE_BOOK_CONTENT(VERSION26, VERSION26),
	HIDE_WRITTEN_BOOK_CONTENT(VERSION26, VERSION26),
	HIDE_TRIM(VERSION26, VERSION26),
	HIDE_DEBUG_STICK_STATE(VERSION26, VERSION26),
	HIDE_ENTITY_DATA(VERSION26, VERSION26),
	HIDE_BUCKET_ENTITY_DATA(VERSION26, VERSION26),
	HIDE_BLOCK_ENTITY_DATA(VERSION26, VERSION26),
	HIDE_INSTRUMENT(VERSION26, VERSION26),
	HIDE_PROVIDES_TRIM_MATERIAL(VERSION26, VERSION26),
	HIDE_OMINOUS_BOTTLE_AMPLIFIER(VERSION26, VERSION26),
	HIDE_JUKEBOX_PLAYABLE(VERSION26, VERSION26),
	HIDE_PROVIDES_BANNER_PATTERNS(VERSION26, VERSION26),
	HIDE_RECIPES(VERSION26, VERSION26),
	HIDE_LODESTONE_TRACKER(VERSION26, VERSION26),
	HIDE_FIREWORK_EXPLOSION(VERSION26, VERSION26),
	HIDE_FIREWORKS(VERSION26, VERSION26),
	HIDE_PROFILE(VERSION26, VERSION26),
	HIDE_NOTE_BLOCK_SOUND(VERSION26, VERSION26),
	HIDE_BANNER_PATTERNS(VERSION26, VERSION26),
	HIDE_BASE_COLOR(VERSION26, VERSION26),
	HIDE_POT_DECORATIONS(VERSION26, VERSION26),
	HIDE_CONTAINER(VERSION26, VERSION26),
	HIDE_BLOCK_STATE(VERSION26, VERSION26),
	HIDE_BEES(VERSION26, VERSION26),
	HIDE_LOCK(VERSION26, VERSION26),
	HIDE_CONTAINER_LOOT(VERSION26, VERSION26),
	HIDE_BREAK_SOUND(VERSION26, VERSION26),
	HIDE_VILLAGER_VARIANT(VERSION26, VERSION26),
	HIDE_WOLF_VARIANT(VERSION26, VERSION26),
	HIDE_WOLF_SOUND_VARIANT(VERSION26, VERSION26),
	HIDE_WOLF_COLLAR(VERSION26, VERSION26),
	HIDE_FOX_VARIANT(VERSION26, VERSION26),
	HIDE_SALMON_SIZE(VERSION26, VERSION26),
	HIDE_PARROT_VARIANT(VERSION26, VERSION26),
	HIDE_TROPICAL_FISH_PATTERN(VERSION26, VERSION26),
	HIDE_TROPICAL_FISH_BASE_COLOR(VERSION26, VERSION26),
	HIDE_TROPICAL_FISH_PATTERN_COLOR(VERSION26, VERSION26),
	HIDE_MOOSHROOM_VARIANT(VERSION26, VERSION26),
	HIDE_RABBIT_VARIANT(VERSION26, VERSION26),
	HIDE_PIG_VARIANT(VERSION26, VERSION26),
	HIDE_COW_VARIANT(VERSION26, VERSION26),
	HIDE_CHICKEN_VARIANT(VERSION26, VERSION26),
	HIDE_FROG_VARIANT(VERSION26, VERSION26),
	HIDE_HORSE_VARIANT(VERSION26, VERSION26),
	HIDE_PAINTING_VARIANT(VERSION26, VERSION26),
	HIDE_LLAMA_VARIANT(VERSION26, VERSION26),
	HIDE_AXOLOTL_VARIANT(VERSION26, VERSION26),
	HIDE_CAT_VARIANT(VERSION26, VERSION26),
	HIDE_CAT_COLLAR(VERSION26, VERSION26),
	HIDE_SHEEP_COLOR(VERSION26, VERSION26),
	HIDE_SHULKER_COLOR(VERSION26, VERSION26);

	public static boolean[] getDefaultValues() {
		boolean[] defaultValues = new boolean[values().length];
		defaultValues[HIDE_UNBREAKABLE.ordinal()] = true;
		return defaultValues;
	}

	public static List<Boolean> getDefaultValuesList() {
		boolean[] defaultValues = getDefaultValues();
	    List<Boolean> result = new ArrayList<>(defaultValues.length);
	    for (boolean defaultValue : defaultValues) {
	        result.add(defaultValue);
        }
	    return result;
    }

    public final int firstVersion, lastVersion;

    VItemFlag(int firstVersion, int lastVersion) {
        this.firstVersion = firstVersion;
        this.lastVersion = lastVersion;
    }

	@Override
	public String toString() {
		return NameHelper.getNiceEnumName(name(), firstVersion, lastVersion);
	}
}