name: build-releases
run-name: Builds the releases and runs unit tests
on: [push]
jobs:
  editor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
          cache: gradle
      - run: cp .github/editor/build.gradle build.gradle
      - run: cp .github/editor/settings.gradle settings.gradle
      - run: ./gradlew test
      - run: ./gradlew shadowJar
      - run: curl -L -o packr.jar https://github.com/libgdx/packr/releases/download/4.0.0/packr-all-4.0.0.jar
      - run: java -jar packr.jar --platform windows64 --jdk https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u352-b08/OpenJDK8U-jdk_x64_windows_hotspot_8u352b08.zip --executable editor --classpath editor/build/libs/editor-all.jar --mainclass nl.knokko.customitems.editor.Editor --output editor-windows
      - run: cd editor-windows && zip -r editor-windows.zip * && cd ..
      - run: java -jar packr.jar --platform linux64 --jdk https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u352-b08/OpenJDK8U-jdk_x64_linux_hotspot_8u352b08.tar.gz --executable editor --classpath editor/build/libs/editor-all.jar --mainclass nl.knokko.customitems.editor.Editor --output editor-linux
      - run: cd editor-linux && zip -r editor-linux.zip * && cd ..
      - run: java -jar packr.jar --platform mac --jdk https://github.com/adoptium/temurin8-binaries/releases/download/jdk8u352-b08/OpenJDK8U-jdk_x64_mac_hotspot_8u352b08.tar.gz --executable editor --classpath editor/build/libs/editor-all.jar --mainclass nl.knokko.customitems.editor.Editor --output editor-macosx
      - run: cd editor-macosx && zip -r editor-macosx.zip * && cd ..
      - uses: actions/upload-artifact@v4
        with:
          name: editor
          path: editor/build/libs/editor-all.jar
      - uses: actions/upload-artifact@v4
        with:
          name: editor-windows
          path: editor-windows/editor-windows.zip
      - uses: actions/upload-artifact@v4
        with:
          name: editor-linux
          path: editor-linux/editor-linux.zip
      - uses: actions/upload-artifact@v4
        with:
          name: editor-macosx
          path: editor-macosx/editor-macosx.zip
  plug-in:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 8
          cache: gradle
      - run: cp .github/plug-in/build.gradle build.gradle
      - run: cp .github/plug-in/settings.gradle settings.gradle
      - run: ./gradlew test
      - run: ./gradlew shadowJar
      - uses: actions/upload-artifact@v4
        with:
          name: plug-in-incomplete
          path: plug-in/build/libs/plug-in-all.jar
  mc1-12:
    runs-on: ubuntu-latest
    container:
      image: knokkogator/kci:0.1.2-mc1.12
    steps:
      - uses: actions/checkout@v4
      - run: cp .github/mc1.12/build.gradle build.gradle
      - run: cp .github/mc1.12/settings.gradle settings.gradle
      - run: ./gradlew build --no-daemon
      - uses: actions/upload-artifact@v4
        with:
          name: kci-nms12
          path: kci-nms12/build/classes/java/main
  mc1-13:
    runs-on: ubuntu-latest
    container:
      image: knokkogator/kci:0.1.2-mc1.13
    steps:
      - uses: actions/checkout@v4
      - run: cp .github/mc1.13/build.gradle build.gradle
      - run: cp .github/mc1.13/settings.gradle settings.gradle
      - run: ./gradlew build --no-daemon
      - uses: actions/upload-artifact@v4
        with:
          name: kci-nms13
          path: kci-nms13/build/classes/java/main
      - uses: actions/upload-artifact@v4
        with:
          name: kci-nms13plus
          path: kci-nms13plus/build/classes/java/main
  mc1-14:
    runs-on: ubuntu-latest
    container:
      image: knokkogator/kci:0.1.2-mc1.14
    steps:
      - uses: actions/checkout@v4
      - run: cp .github/mc1.14/build.gradle build.gradle
      - run: cp .github/mc1.14/settings.gradle settings.gradle
      - run: ./gradlew build --no-daemon
      - uses: actions/upload-artifact@v4
        with:
          name: kci-nms14
          path: kci-nms14/build/classes/java/main
  mc1-15:
    runs-on: ubuntu-latest
    container:
      image: knokkogator/kci:0.1.2-mc1.15
    steps:
      - uses: actions/checkout@v4
      - run: cp .github/mc1.15/build.gradle build.gradle
      - run: cp .github/mc1.15/settings.gradle settings.gradle
      - run: ./gradlew build --no-daemon
      - uses: actions/upload-artifact@v4
        with:
          name: kci-nms15
          path: kci-nms15/build/classes/java/main
  mc1-16:
    runs-on: ubuntu-latest
    container:
      image: knokkogator/kci:0.1.2-mc1.16
    steps:
      - uses: actions/checkout@v4
      - run: cp .github/mc1.16/build.gradle build.gradle
      - run: cp .github/mc1.16/settings.gradle settings.gradle
      - run: ./gradlew build --no-daemon
      - uses: actions/upload-artifact@v4
        with:
          name: kci-nms16
          path: kci-nms16/build/classes/java/main
      - uses: actions/upload-artifact@v4
        with:
          name: kci-nms16plus
          path: kci-nms16plus/build/classes/java/main
  mc1-17:
    runs-on: ubuntu-latest
    container:
      image: knokkogator/kci:0.1.2-mc1.17
    steps:
      - uses: actions/checkout@v4
      - run: cp .github/mc1.17/build.gradle build.gradle
      - run: cp .github/mc1.17/settings.gradle settings.gradle
      - run: ./gradlew build --no-daemon
      - uses: actions/upload-artifact@v4
        with:
          name: kci-nms17
          path: kci-nms17/build/classes/java/main
  mc1-18:
    runs-on: ubuntu-latest
    container:
      image: knokkogator/kci:0.1.2-mc1.18
    steps:
      - uses: actions/checkout@v4
      - run: cp .github/mc1.18/build.gradle build.gradle
      - run: cp .github/mc1.18/settings.gradle settings.gradle
      - run: ./gradlew build --no-daemon
      - uses: actions/upload-artifact@v4
        with:
          name: kci-nms18
          path: kci-nms18/build/classes/java/main
      - uses: actions/upload-artifact@v4
        with:
          name: kci-nms18plus
          path: kci-nms18plus/build/classes/java/main
  mc1-19:
    runs-on: ubuntu-latest
    container:
      image: knokkogator/kci:0.1.2-mc1.19
    steps:
      - uses: actions/checkout@v4
      - run: cp .github/mc1.19/build.gradle build.gradle
      - run: cp .github/mc1.19/settings.gradle settings.gradle
      - run: ./gradlew build --no-daemon
      - uses: actions/upload-artifact@v4
        with:
          name: kci-nms19
          path: kci-nms19/build/classes/java/main
  mc1-20:
    runs-on: ubuntu-latest
    container:
      image: knokkogator/kci:0.1.2-mc1.20
    steps:
      - uses: actions/checkout@v4
      - run: cp .github/mc1.20/build.gradle build.gradle
      - run: cp .github/mc1.20/settings.gradle settings.gradle
      - run: ./gradlew build
      - run: ./gradlew shadowJar
      - uses: actions/upload-artifact@v4
        with:
          name: kci-nms20
          path: kci-nms20/build/libs/kci-nms20-all.jar
  mc1-21:
    runs-on: ubuntu-latest
    container:
      image: knokkogator/kci:0.1.5-mc1.21
    steps:
      - uses: actions/checkout@v4
      - run: cp .github/mc1.21/build.gradle build.gradle
      - run: cp .github/mc1.21/settings.gradle settings.gradle
      - run: ./gradlew build --no-daemon
      - uses: actions/upload-artifact@v4
        with:
          name: kci-nms21
          path: kci-nms21/build/classes/java/main
      - uses: actions/upload-artifact@v4
        with:
          name: kci-nms21plus
          path: kci-nms21plus/build/classes/java/main
  ce-event-handler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: gradle
      - run: cp .github/ce-event-handler/build.gradle build.gradle
      - run: cp .github/ce-event-handler/settings.gradle settings.gradle
      - run: ./gradlew build --no-daemon
      - uses: actions/upload-artifact@v4
        with:
          name: ce-event-handler
          path: ce-event-handler/build/classes/java/main
  combine:
    runs-on: ubuntu-latest
    needs: [editor, plug-in, mc1-12, mc1-13, mc1-14, mc1-15, mc1-16, mc1-17, mc1-18, mc1-19, mc1-20, mc1-21, ce-event-handler]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: plug-in-incomplete
          path: combined
      - uses: actions/download-artifact@v4
        with:
          name: ce-event-handler
          path: combined
      - uses: actions/download-artifact@v4
        with:
          name: kci-nms12
          path: combined
      - uses: actions/download-artifact@v4
        with:
          name: kci-nms13
          path: combined
      - uses: actions/download-artifact@v4
        with:
          name: kci-nms13plus
          path: combined
      - uses: actions/download-artifact@v4
        with:
          name: kci-nms14
          path: combined
      - uses: actions/download-artifact@v4
        with:
          name: kci-nms15
          path: combined
      - uses: actions/download-artifact@v4
        with:
          name: kci-nms16
          path: combined
      - uses: actions/download-artifact@v4
        with:
          name: kci-nms16plus
          path: combined
      - uses: actions/download-artifact@v4
        with:
          name: kci-nms17
          path: combined
      - uses: actions/download-artifact@v4
        with:
          name: kci-nms18
          path: combined
      - uses: actions/download-artifact@v4
        with:
          name: kci-nms18plus
          path: combined
      - uses: actions/download-artifact@v4
        with:
          name: kci-nms19
          path: combined
      - uses: actions/download-artifact@v4
        with:
          name: kci-nms20
          path: combined
      - uses: actions/download-artifact@v4
        with:
          name: kci-nms21plus
          path: combined
      - uses: actions/download-artifact@v4
        with:
          name: kci-nms21
          path: combined
      - run: unzip -d combined combined/kci-nms20-all.jar
      - run: rm combined/kci-nms20-all.jar
      - run: unzip -d combined -o combined/plug-in-all.jar
      - run: rm combined/plug-in-all.jar
      - run: cd combined && zip -r CustomItems.jar * && cd ..
      - run: mkdir releases
      - run: cp combined/CustomItems.jar releases/CustomItems.jar
      - uses: actions/download-artifact@v4
        with:
          name: editor
          path: releases
      - run: cp releases/editor-all.jar releases/Editor.jar
      - run: rm releases/editor-all.jar
      - uses: actions/download-artifact@v4
        with:
          name: editor-windows
          path: releases
      - uses: actions/download-artifact@v4
        with:
          name: editor-linux
          path: releases
      - uses: actions/download-artifact@v4
        with:
          name: editor-macosx
          path: releases
      - uses: actions/upload-artifact@v4
        with:
          name: releases
          path: releases
